# Generated by Django 4.2.3 on 2023-07-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('CE', 'Caixa Economica'), ('BA', 'Bradesco'), ('IT', 'Inter'), ('SC', 'Sicoob'), ('NU', 'Nubank')], max_length=2),
        ),
    ]
